// <auto-generated />
using System;
using GerenciamentoComercio_Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GerenciamentoComercio_Infra.Migrations
{
    [DbContext(typeof(GerenciamentoComercioContext))]
    partial class GerenciamentoComercioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("latecher")
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GerenciamentoComercio_Infra.Models.Access", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATION_DATE");

                    b.Property<string>("CreationUser")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("CREATION_USER");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Type")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("TYPE");

                    b.HasKey("Id");

                    b.ToTable("ACCESS");
                });

            modelBuilder.Entity("GerenciamentoComercio_Infra.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("ADDRESS");

                    b.Property<string>("Cpf")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("CPF");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATION_DATE");

                    b.Property<string>("CreationUser")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("CREATION_USER");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FullName")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("FULL_NAME");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("PHONE");

                    b.HasKey("Id");

                    b.ToTable("CLIENT");
                });

            modelBuilder.Entity("GerenciamentoComercio_Infra.Models.ClientTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATION_DATE");

                    b.Property<string>("CreationUser")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("CREATION_USER");

                    b.Property<double?>("DiscountPercentage")
                        .HasColumnType("float")
                        .HasColumnName("DISCOUNT_PERCENTAGE");

                    b.Property<decimal?>("DiscountPrice")
                        .HasColumnType("money")
                        .HasColumnName("DISCOUNT_PRICE");

                    b.Property<int?>("IdClient")
                        .HasColumnType("int")
                        .HasColumnName("ID_CLIENT");

                    b.Property<int?>("IdEmployee")
                        .HasColumnType("int")
                        .HasColumnName("ID_EMPLOYEE");

                    b.Property<string>("Observations")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("OBSERVATIONS");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("money")
                        .HasColumnName("TOTAL_PRICE");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdEmployee");

                    b.ToTable("CLIENT_TRANSACTION");
                });

            modelBuilder.Entity("GerenciamentoComercio_Infra.Models.ClientTransactionProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATION_DATE");

                    b.Property<string>("CreationUser")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("CREATION_USER");

                    b.Property<int?>("IdClientTransaction")
                        .HasColumnType("int")
                        .HasColumnName("ID_CLIENT_TRANSACTION");

                    b.Property<int?>("IdProduct")
                        .HasColumnType("int")
                        .HasColumnName("ID_PRODUCT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("money")
                        .HasColumnName("PRICE");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("QUANTITY");

                    b.HasKey("Id");

                    b.HasIndex("IdClientTransaction");

                    b.HasIndex("IdProduct");

                    b.ToTable("CLIENT_TRANSACTION_PRODUCT");
                });

            modelBuilder.Entity("GerenciamentoComercio_Infra.Models.ClientTransactionService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATION_DATE");

                    b.Property<string>("CreationUser")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("CREATION_USER");

                    b.Property<int?>("IdClientTransaction")
                        .HasColumnType("int")
                        .HasColumnName("ID_CLIENT_TRANSACTION");

                    b.Property<int?>("IdService")
                        .HasColumnType("int")
                        .HasColumnName("ID_SERVICE");

                    b.Property<decimal?>("Price")
                        .HasColumnType("money")
                        .HasColumnName("PRICE");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("QUANTITY");

                    b.HasKey("Id");

                    b.HasIndex("IdClientTransaction");

                    b.HasIndex("IdService");

                    b.ToTable("CLIENT_TRANSACTION_SERVICE");
                });

            modelBuilder.Entity("GerenciamentoComercio_Infra.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Access")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("ACCESS");

                    b.Property<string>("Address")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("ADDRESS");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATION_DATE");

                    b.Property<string>("CreationUser")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("CREATION_USER");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FullName")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("FULL_NAME");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<bool?>("IsAdministrator")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ADMINISTRATOR");

                    b.Property<string>("Password")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Phone")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("PHONE");

                    b.HasKey("Id");

                    b.ToTable("EMPLOYEE");
                });

            modelBuilder.Entity("GerenciamentoComercio_Infra.Models.EmployeeAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATION_DATE");

                    b.Property<string>("CreationUser")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("CREATION_USER");

                    b.Property<int?>("IdAccess")
                        .HasColumnType("int")
                        .HasColumnName("ID_ACCESS");

                    b.Property<int?>("IdEmployee")
                        .HasColumnType("int")
                        .HasColumnName("ID_EMPLOYEE");

                    b.HasKey("Id");

                    b.HasIndex("IdAccess");

                    b.HasIndex("IdEmployee");

                    b.ToTable("EMPLOYEE_ACCESS");
                });

            modelBuilder.Entity("GerenciamentoComercio_Infra.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATION_DATE");

                    b.Property<string>("CreationUser")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("CREATION_USER");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<int?>("IdProductCategory")
                        .HasColumnType("int")
                        .HasColumnName("ID_PRODUCT_CATEGORY");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.HasIndex("IdProductCategory");

                    b.ToTable("PRODUCT");
                });

            modelBuilder.Entity("GerenciamentoComercio_Infra.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATION_DATE");

                    b.Property<string>("CreationUser")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("CREATION_USER");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Title")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("TITLE");

                    b.HasKey("Id");

                    b.ToTable("PRODUCT_CATEGORY");
                });

            modelBuilder.Entity("GerenciamentoComercio_Infra.Models.ProductHistoric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATION_DATE");

                    b.Property<string>("CreationUser")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("CREATION_USER");

                    b.Property<int?>("IdProduct")
                        .HasColumnType("int")
                        .HasColumnName("ID_PRODUCT");

                    b.Property<int?>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("ID_USER");

                    b.Property<decimal?>("Price")
                        .HasColumnType("money")
                        .HasColumnName("PRICE");

                    b.Property<long?>("Quantity")
                        .HasColumnType("bigint")
                        .HasColumnName("QUANTITY");

                    b.HasKey("Id");

                    b.HasIndex("IdProduct");

                    b.ToTable("PRODUCT_HISTORIC");
                });

            modelBuilder.Entity("GerenciamentoComercio_Infra.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATION_DATE");

                    b.Property<string>("CreationUser")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("CREATION_USER");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<int?>("IdServiceCategory")
                        .HasColumnType("int")
                        .HasColumnName("ID_SERVICE_CATEGORY");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("NAME");

                    b.Property<decimal?>("Sla")
                        .HasColumnType("money")
                        .HasColumnName("SLA");

                    b.HasKey("Id");

                    b.HasIndex("IdServiceCategory");

                    b.ToTable("SERVICE");
                });

            modelBuilder.Entity("GerenciamentoComercio_Infra.Models.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATION_DATE");

                    b.Property<string>("CreationUser")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("CREATION_USER");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Title")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("TITLE");

                    b.HasKey("Id");

                    b.ToTable("SERVICE_CATEGORY");
                });

            modelBuilder.Entity("GerenciamentoComercio_Infra.Models.ServiceHistoric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATION_DATE");

                    b.Property<string>("CreationUser")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("CREATION_USER");

                    b.Property<int?>("IdService")
                        .HasColumnType("int")
                        .HasColumnName("ID_SERVICE");

                    b.Property<int?>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("ID_USER");

                    b.Property<decimal?>("Price")
                        .HasColumnType("money")
                        .HasColumnName("PRICE");

                    b.Property<decimal?>("Sla")
                        .HasColumnType("money")
                        .HasColumnName("SLA");

                    b.HasKey("Id");

                    b.HasIndex("IdService");

                    b.ToTable("SERVICE_HISTORIC");
                });

            modelBuilder.Entity("GerenciamentoComercio_Infra.Models.ClientTransaction", b =>
                {
                    b.HasOne("GerenciamentoComercio_Infra.Models.Client", "IdClientNavigation")
                        .WithMany("ClientTransaction")
                        .HasForeignKey("IdClient")
                        .HasConstraintName("FK__CLIENT_TR__ID_CL__36B12243");

                    b.HasOne("GerenciamentoComercio_Infra.Models.Employee", "IdEmployeeNavigation")
                        .WithMany("ClientTransaction")
                        .HasForeignKey("IdEmployee")
                        .HasConstraintName("FK__CLIENT_TR__ID_EM__37A5467C");

                    b.Navigation("IdClientNavigation");

                    b.Navigation("IdEmployeeNavigation");
                });

            modelBuilder.Entity("GerenciamentoComercio_Infra.Models.ClientTransactionProduct", b =>
                {
                    b.HasOne("GerenciamentoComercio_Infra.Models.ClientTransaction", "IdClientTransactionNavigation")
                        .WithMany("ClientTransactionProduct")
                        .HasForeignKey("IdClientTransaction")
                        .HasConstraintName("FK__CLIENT_TR__ID_CL__440B1D61");

                    b.HasOne("GerenciamentoComercio_Infra.Models.Product", "IdProductNavigation")
                        .WithMany("ClientTransactionProduct")
                        .HasForeignKey("IdProduct")
                        .HasConstraintName("FK__CLIENT_TR__ID_PR__44FF419A");

                    b.Navigation("IdClientTransactionNavigation");

                    b.Navigation("IdProductNavigation");
                });

            modelBuilder.Entity("GerenciamentoComercio_Infra.Models.ClientTransactionService", b =>
                {
                    b.HasOne("GerenciamentoComercio_Infra.Models.ClientTransaction", "IdClientTransactionNavigation")
                        .WithMany("ClientTransactionService")
                        .HasForeignKey("IdClientTransaction")
                        .HasConstraintName("FK__CLIENT_TR__ID_CL__403A8C7D");

                    b.HasOne("GerenciamentoComercio_Infra.Models.Service", "IdServiceNavigation")
                        .WithMany("ClientTransactionService")
                        .HasForeignKey("IdService")
                        .HasConstraintName("FK__CLIENT_TR__ID_SE__412EB0B6");

                    b.Navigation("IdClientTransactionNavigation");

                    b.Navigation("IdServiceNavigation");
                });

            modelBuilder.Entity("GerenciamentoComercio_Infra.Models.EmployeeAccess", b =>
                {
                    b.HasOne("GerenciamentoComercio_Infra.Models.Access", "IdAccessNavigation")
                        .WithMany("EmployeeAccess")
                        .HasForeignKey("IdAccess")
                        .HasConstraintName("FK__EMPLOYEE___ID_AC__3D5E1FD2");

                    b.HasOne("GerenciamentoComercio_Infra.Models.Employee", "IdEmployeeNavigation")
                        .WithMany("EmployeeAccess")
                        .HasForeignKey("IdEmployee")
                        .HasConstraintName("FK__EMPLOYEE___ID_EM__3C69FB99");

                    b.Navigation("IdAccessNavigation");

                    b.Navigation("IdEmployeeNavigation");
                });

            modelBuilder.Entity("GerenciamentoComercio_Infra.Models.Product", b =>
                {
                    b.HasOne("GerenciamentoComercio_Infra.Models.ProductCategory", "IdProductCategoryNavigation")
                        .WithMany("Product")
                        .HasForeignKey("IdProductCategory")
                        .HasConstraintName("FK__PRODUCT__ID_PROD__2E1BDC42");

                    b.Navigation("IdProductCategoryNavigation");
                });

            modelBuilder.Entity("GerenciamentoComercio_Infra.Models.ProductHistoric", b =>
                {
                    b.HasOne("GerenciamentoComercio_Infra.Models.Product", "IdProductNavigation")
                        .WithMany("ProductHistoric")
                        .HasForeignKey("IdProduct")
                        .HasConstraintName("FK__PRODUCT_H__ID_PR__33D4B598");

                    b.Navigation("IdProductNavigation");
                });

            modelBuilder.Entity("GerenciamentoComercio_Infra.Models.Service", b =>
                {
                    b.HasOne("GerenciamentoComercio_Infra.Models.ServiceCategory", "IdServiceCategoryNavigation")
                        .WithMany("Service")
                        .HasForeignKey("IdServiceCategory")
                        .HasConstraintName("FK__SERVICE__ID_SERV__2B3F6F97");

                    b.Navigation("IdServiceCategoryNavigation");
                });

            modelBuilder.Entity("GerenciamentoComercio_Infra.Models.ServiceHistoric", b =>
                {
                    b.HasOne("GerenciamentoComercio_Infra.Models.Service", "IdServiceNavigation")
                        .WithMany("ServiceHistoric")
                        .HasForeignKey("IdService")
                        .HasConstraintName("FK__SERVICE_H__ID_SE__30F848ED");

                    b.Navigation("IdServiceNavigation");
                });

            modelBuilder.Entity("GerenciamentoComercio_Infra.Models.Access", b =>
                {
                    b.Navigation("EmployeeAccess");
                });

            modelBuilder.Entity("GerenciamentoComercio_Infra.Models.Client", b =>
                {
                    b.Navigation("ClientTransaction");
                });

            modelBuilder.Entity("GerenciamentoComercio_Infra.Models.ClientTransaction", b =>
                {
                    b.Navigation("ClientTransactionProduct");

                    b.Navigation("ClientTransactionService");
                });

            modelBuilder.Entity("GerenciamentoComercio_Infra.Models.Employee", b =>
                {
                    b.Navigation("ClientTransaction");

                    b.Navigation("EmployeeAccess");
                });

            modelBuilder.Entity("GerenciamentoComercio_Infra.Models.Product", b =>
                {
                    b.Navigation("ClientTransactionProduct");

                    b.Navigation("ProductHistoric");
                });

            modelBuilder.Entity("GerenciamentoComercio_Infra.Models.ProductCategory", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("GerenciamentoComercio_Infra.Models.Service", b =>
                {
                    b.Navigation("ClientTransactionService");

                    b.Navigation("ServiceHistoric");
                });

            modelBuilder.Entity("GerenciamentoComercio_Infra.Models.ServiceCategory", b =>
                {
                    b.Navigation("Service");
                });
#pragma warning restore 612, 618
        }
    }
}
